[toolchain]
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vangai = "9hUyPGeYFxdfrp5XmrkaVoEbB1V8hjuigXdUAM7LQTXi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"

[anchor]
workspace = "workspace"
idl = "target/idl"
typescript = "target/types"